basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API performing integration tests against Stacks
  title: Stacks Integration API
  version: "1.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
